language: node_js

node_js:
  - "8"
  - "9"
  - "node"

sudo: false

branches:
   only:
   - master

cache:
  directories:
    - "node_modules"

script:
  - "npm run lint"
  - "npm run test"

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm run coveralls
